# Generated by Django 5.2.7 on 2025-10-04 04:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='과목명')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='과목코드')),
                ('professor', models.CharField(blank=True, max_length=50, verbose_name='교수명')),
                ('credits', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='학점')),
                ('subject_type', models.CharField(choices=[('MAJOR', '전공'), ('GENERAL', '교양'), ('MILITARY', '군사학'), ('PHYSICAL', '체육'), ('OTHER', '기타')], default='MAJOR', max_length=10, verbose_name='과목 구분')),
                ('evaluation_type', models.CharField(choices=[('EXAM', '시험'), ('REPORT', '보고서'), ('PRESENTATION', '발표'), ('PROJECT', '프로젝트'), ('PARTICIPATION', '참여도'), ('MIXED', '혼합')], default='EXAM', max_length=15, verbose_name='평가 방식')),
                ('classroom', models.CharField(blank=True, max_length=50, verbose_name='강의실')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='메모')),
                ('color', models.CharField(default='#007bff', help_text='시간표에서 표시될 색상 (HEX 코드)', max_length=7, verbose_name='색상')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '과목',
                'verbose_name_plural': '과목들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='년도')),
                ('semester', models.CharField(choices=[('SPRING', '1학기'), ('SUMMER', '여름학기'), ('FALL', '2학기'), ('WINTER', '겨울학기')], max_length=10, verbose_name='학기')),
                ('is_current', models.BooleanField(default=False, verbose_name='현재 학기')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학기',
                'verbose_name_plural': '학기들',
                'ordering': ['-year', '-semester'],
                'unique_together': {('user', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', '월요일'), ('TUE', '화요일'), ('WED', '수요일'), ('THU', '목요일'), ('FRI', '금요일'), ('SAT', '토요일'), ('SUN', '일요일')], max_length=3, verbose_name='요일')),
                ('period', models.IntegerField(choices=[(1, '1교시 (09:00-09:50)'), (2, '2교시 (10:00-10:50)'), (3, '3교시 (11:00-11:50)'), (4, '4교시 (12:00-12:50)'), (5, '5교시 (13:00-13:50)'), (6, '6교시 (14:00-14:50)'), (7, '7교시 (15:00-15:50)'), (8, '8교시 (16:00-16:50)'), (9, '9교시 (17:00-17:50)'), (10, '10교시 (18:00-18:50)')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='교시')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='장소')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='timetable.subject')),
            ],
            options={
                'verbose_name': '시간표 슬롯',
                'verbose_name_plural': '시간표 슬롯들',
                'ordering': ['day', 'period'],
                'unique_together': {('subject', 'day', 'period')},
            },
        ),
    ]
