# Generated by Django 5.2.7 on 2025-10-04 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='period',
            field=models.IntegerField(choices=[(1, '1교시 (08:10-09:00)'), (2, '2교시 (09:10-10:00)'), (3, '3교시 (10:10-11:00)'), (4, '4교시 (11:10-12:00)'), (5, '5교시 (13:00-13:50)'), (6, '6교시 (14:00-14:50)'), (7, '7교시 (15:10-16:00)'), (8, '8교시 (16:10-17:00)')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='교시'),
        ),
    ]
