# Generated by Django 4.2.25 on 2025-10-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_remove_subject_code_remove_subject_evaluation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('MON', '월요일'), ('TUE', '화요일'), ('WED', '수요일'), ('THU', '목요일'), ('FRI', '금요일')], max_length=3, verbose_name='요일'),
        ),
    ]
