# Generated by Django 5.2.7 on 2025-11-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_timeslot_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('SPRING', '1학기'), ('FALL', '2학기'), ('WINTER', '겨울학기')], max_length=10, verbose_name='학기'),
        ),
    ]
