# Generated by Django 5.2.7 on 2025-12-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_semester_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('SPRING', '1학기'), ('FALL', '2학기'), ('WINTER', '동계학기')], max_length=10, verbose_name='학기'),
        ),
    ]
