# Generated by Django 5.2.7 on 2025-12-10 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_semester_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(6)], verbose_name='학점'),
        ),
    ]
