# Generated by Django 5.2.7 on 2025-12-22 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_alter_subject_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=1, default=3, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='학점'),
        ),
    ]
