# Generated by Django 5.2.7 on 2025-12-22 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_alter_subject_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('SYLLABUS', '강의계획서'), ('LECTURE', '수업자료'), ('ASSIGNMENT', '과제'), ('EXAM', '시험자료'), ('REFERENCE', '참고자료'), ('OTHER', '기타')], default='OTHER', max_length=20, verbose_name='파일 종류')),
                ('title', models.CharField(max_length=200, verbose_name='파일 제목')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='설명')),
                ('file', models.FileField(upload_to='subject_files/%Y/%m/', verbose_name='파일')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='파일 크기')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='timetable.subject')),
            ],
            options={
                'verbose_name': '과목 파일',
                'verbose_name_plural': '과목 파일들',
                'ordering': ['-created_at'],
            },
        ),
    ]
