# Generated by Django 5.2.7 on 2025-12-26 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_subjectfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='timetable.semester', verbose_name='학기'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('semester', 'day', 'period')},
        ),
    ]
