# Generated by Django 5.2.7 on 2025-12-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_alter_timeslot_unique_together_timeslot_semester_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
    ]
