# Generated by Django 5.2.7 on 2025-10-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('INTL', '국제관계학과'), ('DEFENSE', '국방경영학과'), ('AERO_POLICY', '항공우주정책학과'), ('COMP', '컴퓨터과학과'), ('AERO', '항공공학과'), ('SPACE', '우주공학과'), ('MECH', '기계공학과'), ('ELEC', '전자통신공학과'), ('SYSTEM', '시스템공학과')], default='COMP', max_length=15, verbose_name='학과'),
        ),
    ]
