# Generated by Django 5.2.7 on 2025-12-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_choice',
            field=models.CharField(choices=[('default', '기본 아바타'), ('student_male', '남학생'), ('student_female', '여학생'), ('soldier', '군인'), ('pilot', '조종사'), ('engineer', '엔지니어'), ('scientist', '과학자'), ('astronaut', '우주비행사')], default='default', max_length=20, verbose_name='아바타 선택'),
        ),
    ]
