# Generated by Django 5.2.7 on 2025-12-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_study_goal',
            field=models.PositiveIntegerField(default=40, verbose_name='주간 학습 목표(시간)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_choice',
            field=models.CharField(blank=True, default='default', max_length=20, verbose_name='아바타 선택 (legacy)'),
        ),
    ]
