# Generated by Django 5.2.7 on 2025-11-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('STUDY_SHARE', '학습 자료 공유'), ('FITNESS_TIPS', '체력 평가 팁'), ('SCHOOL_TIPS', '학교 생활 팁'), ('CUSTOM', '직접 입력'), ('STUDY', '학습 자료'), ('EXAM', '시험 정보'), ('LECTURE', '강의 특성'), ('FITNESS', '체력평가'), ('ENGLISH', '영어 상식'), ('PROJECT', '프로젝트'), ('QNA', '질문답변'), ('FREE', '자유게시판'), ('NOTICE', '공지사항')], default='FREE', max_length=15, verbose_name='카테고리 유형'),
        ),
    ]
