# Generated by Django 5.2.7 on 2025-12-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('STUDY', '학습 자료'), ('EXAM', '시험 정보'), ('LECTURE', '강의 특성'), ('FITNESS', '체력평가'), ('ENGLISH', '영어상식'), ('PROJECT', '프로젝트'), ('QNA', '질문답변'), ('FREE', '자유게시판'), ('NOTICE', '공지사항')], default='FREE', max_length=10, verbose_name='카테고리 유형'),
        ),
    ]
