# Generated by Django 5.2.7 on 2025-12-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_category_category_type'),
        ('community', '0004_post_bookmarks'),
    ]

    operations = [
    ]
