# Generated by Django 5.2.7 on 2025-12-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_merge_20251226_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NORMAL', '일반'), ('QUESTION', '질문'), ('NOTICE', '공지'), ('TIP', '팁')], default='NORMAL', max_length=10, verbose_name='게시글 유형'),
        ),
    ]
