# Generated by Django 5.2.7 on 2025-10-04 11:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        ('timetable', '0002_alter_timeslot_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='날짜')),
                ('daily_goal', models.TextField(blank=True, verbose_name='오늘의 목표')),
                ('target_study_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(24.0)], verbose_name='목표 학습시간(시간)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_planners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일일 플래너',
                'verbose_name_plural': '일일 플래너들',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='할 일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('priority', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음')], default='MEDIUM', max_length=10, verbose_name='우선순위')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to='planner.dailyplanner')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_items', to='timetable.subject', verbose_name='관련 과목')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_items', to='planner.task', verbose_name='관련 과제')),
            ],
            options={
                'verbose_name': '할 일',
                'verbose_name_plural': '할 일들',
                'ordering': ['order', '-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(23)], verbose_name='시간 (6-23)')),
                ('minute_block', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='10분 블록 (0-5: 00,10,20,30,40,50분)')),
                ('block_type', models.CharField(choices=[('STUDY', '학습'), ('BREAK', '휴식'), ('MEAL', '식사'), ('EXERCISE', '운동'), ('OTHER', '기타')], default='STUDY', max_length=10, verbose_name='블록 유형')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='색상')),
                ('memo', models.CharField(blank=True, max_length=100, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='planner.dailyplanner')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_blocks', to='timetable.subject', verbose_name='관련 과목')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_blocks', to='planner.task', verbose_name='관련 과제')),
            ],
            options={
                'verbose_name': '시간 블록',
                'verbose_name_plural': '시간 블록들',
                'ordering': ['hour', 'minute_block'],
                'unique_together': {('daily_planner', 'hour', 'minute_block')},
            },
        ),
    ]
