# Generated by Django 5.2.7 on 2025-12-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_todoitem_task_todoitem_estimated_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='target_hours',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_tasks',
        ),
        migrations.AddField(
            model_name='goal',
            name='memo',
            field=models.TextField(blank=True, verbose_name='메모'),
        ),
    ]
