# Generated by Django 5.2.7 on 2025-12-14 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_remove_goal_target_hours_remove_goal_target_tasks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': '목표', 'verbose_name_plural': '목표들'},
        ),
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='진행률(%)'),
        ),
    ]
