# Generated by Django 5.2.7 on 2025-12-19 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_add_goal_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='hour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='시간 (0-23)'),
        ),
    ]
