# Generated by Django 5.2.7 on 2025-12-24 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_timeblock_hour_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='하위 목표')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='planner.goal', verbose_name='상위 목표')),
            ],
            options={
                'verbose_name': '하위 목표',
                'verbose_name_plural': '하위 목표들',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
