# Generated by Django 5.2.7 on 2025-10-04 04:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='목표 제목')),
                ('description', models.TextField(blank=True, verbose_name='목표 설명')),
                ('goal_type', models.CharField(choices=[('DAILY', '일일 목표'), ('WEEKLY', '주간 목표'), ('MONTHLY', '월간 목표'), ('SEMESTER', '학기 목표'), ('CUSTOM', '사용자 정의')], default='WEEKLY', max_length=10, verbose_name='목표 유형')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('target_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(999.99)], verbose_name='목표 학습시간(시간)')),
                ('target_tasks', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='목표 과제 수')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='달성 여부')),
                ('achievement_date', models.DateTimeField(blank=True, null=True, verbose_name='달성일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학습 목표',
                'verbose_name_plural': '학습 목표들',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('category', models.CharField(choices=[('ASSIGNMENT', '과제'), ('EXAM', '시험'), ('PROJECT', '프로젝트'), ('STUDY', '학습'), ('PERSONAL', '개인'), ('OTHER', '기타')], default='ASSIGNMENT', max_length=15, verbose_name='카테고리')),
                ('priority', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('URGENT', '긴급')], default='MEDIUM', max_length=10, verbose_name='우선순위')),
                ('status', models.CharField(choices=[('TODO', '할 일'), ('IN_PROGRESS', '진행 중'), ('COMPLETED', '완료'), ('CANCELLED', '취소')], default='TODO', max_length=15, verbose_name='상태')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='마감일')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(999.99)], verbose_name='예상 소요시간(시간)')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(999.99)], verbose_name='실제 소요시간(시간)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='진행률(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='timetable.subject', verbose_name='관련 과목')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '과제/할일',
                'verbose_name_plural': '과제/할일들',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='세션 제목')),
                ('description', models.TextField(blank=True, verbose_name='학습 내용')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='소요시간(분)')),
                ('effectiveness_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='효과성 평가(1-5)')),
                ('notes', models.TextField(blank=True, verbose_name='학습 노트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='timetable.subject', verbose_name='관련 과목')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='planner.task', verbose_name='관련 과제')),
            ],
            options={
                'verbose_name': '학습 세션',
                'verbose_name_plural': '학습 세션들',
                'ordering': ['-start_time'],
            },
        ),
    ]
