# Generated by Django 5.2.7 on 2025-10-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_dailyplanner_todoitem_timeblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='task',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='예상 소요시간(분)'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('in_progress', '진행중'), ('completed', '완료')], default='pending', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='상세 설명'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음')], default='medium', max_length=20, verbose_name='우선순위'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='subject',
            field=models.CharField(choices=[('math', '수학'), ('korean', '국어'), ('english', '영어'), ('history', '역사'), ('science', '과학'), ('military', '군사학'), ('physical', '체육'), ('other', '기타')], default='other', max_length=20, verbose_name='과목'),
        ),
    ]
